parameters:
  ########## PRODUCER CLASSES  ##########
  smartesb.producers.direct.class: Smartbox\Integration\FrameworkBundle\Core\Producers\DirectProducer
  smartesb.producers.json_file.class: Smartbox\Integration\FrameworkBundle\Components\JsonFileLoader\JsonFileLoaderProducer
  smartesb.producers.service.class: Smartbox\Integration\FrameworkBundle\Components\SymfonyService\SymfonyServiceProducer
  smartesb.producers.csv_file.class: Smartbox\Integration\FrameworkBundle\Components\FileService\Csv\CsvConfigurableProducer

services:
  ########## PRODUCERS  ##########
  smartesb.producer.direct:
      class: "%smartesb.producers.direct.class%"
      calls:
        - [setId, ['smartesb.producer.direct']]
        - [setItineraryResolver, ['@smartesb.itineray_resolver']]
      public: true

  smartesb.producers.json_file:
      class: "%smartesb.producers.json_file.class%"
      calls:
        - [setId, ['smartesb.producers.json_file']]
        - [setSerializer, ['@jms_serializer']]
      public: true

  # STOMP | AMQP
  smartesb.producers.queue:
      class: Smartbox\Integration\FrameworkBundle\Components\Queues\QueueProducer
      calls:
        - [setId, ['smartesb.producers.queue']]
        - [setSerializer, ['@smartesb.serialization.queue.jms_serializer']]
        - [setDriverRegistry, ['@smartesb.drivers.queue._registry']]
      public: true

  # NoSQL
  smartesb.producers.service:
      class: "%smartesb.producers.service.class%"
      calls:
        - [setId, ['smartesb.producers.service']]
        - [setContainer, ['@service_container']]
      public: true
