name: Workflow
on: [push]
jobs:
  php_8_job:
    runs-on: '${{ matrix.os }}'
    container: ubuntu:latest
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.0']
        include:
          - os: ubuntu-18.04
            SYMFONY_VERSION: 3.4.*
            SYMFONY_PHPUNIT_VERSION: '9.5'

#    services:
#      rabbit:
#        image: rabbitmq:3.8
##        options: --hostname rabbit
#        env:
#          RABBITMQ_DEFAULT_USER: guest
#          RABBITMQ_DEFAULT_PASS: guest
#        ports:
#          - 5672:5672

    steps:
      - uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl,soap,mongodb,apcu   #optional
          ini-values: "post_max_size=256M" #optional
      - name: Install rabbitMQ lib
        run: sudo apt-get install -y rabbitmq-server
      - name: Install rabbitMQ lib
        run: sudo apt-get install -y librabbitmq-dev
      - name: Check PHP Version
        run: php -v
#      - name: Install librabbitmq-dev
#        run: sudo apt install librabbitmq-dev
#      - run: sudo systemctl enable rabbitmq-server
#      - run: sudo rabbitmq-plugins enable rabbitmq_stomp
#      - run: sudo systemctl restart rabbitmq-server
#      - name: Checking rabbitmq
#        run: ping rabbit
      - run: sudo apt-get update
#      - run: sudo pecl install apcu-5.1.19
      - run: sudo systemctl enable rabbitmq-server
      - run: sudo rabbitmq-server -detached
#      - run: sudo systemctl start rabbitmq-server
      - run: sudo rabbitmq-plugins enable rabbitmq_stomp
      - run: sudo rabbitmqctl start_app
      - run: sudo service rabbitmq-server status
      - run: sudo rabbitmqctl list_vhosts
      - run: sudo rabbitmqctl list_bindings
      - run: sudo rabbitmqctl list_connections
      #      - run: sudo systemctl restart rabbitmq-server
      - run: sudo apt-get -y install iputils-ping
#      - name: Checking rabbitmq
#        run: ping rabbit -c 2
      - run: sudo composer self-update
      - run: sudo apt-get install -y libxml2-dev
      - run: >-
          composer require symfony/framework-bundle:${SYMFONY_VERSION}
          --no-update
        env:
          SYMFONY_VERSION: '${{ matrix.SYMFONY_VERSION }}'
          SYMFONY_PHPUNIT_VERSION: '${{ matrix.SYMFONY_PHPUNIT_VERSION }}'
          # The hostname used to communicate with the PostgreSQL service container
#          RABBITMQ_HOST: rabbit
#          RABBITMQ_PORT: ${{ job.services.rabbit.ports[5672] }}
      - run: composer install --prefer-dist --no-interaction
      - run: bin/simple-phpunit --coverage-text

#  php_7_job:
#    runs-on: '${{ matrix.os }}'
#    strategy:
#      matrix:
#        operating-system: [ubuntu-latest]
#        php-versions: ['7.0','7.1','7.2','7.3','7.4']
#        include:
#          - os: ubuntu-18.04
#            SYMFONY_VERSION: 3.4.*
#          - os: ubuntu-18.04
#            SYMFONY_VERSION: 5.4.*
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: ${{ matrix.php-versions }}
#          extensions: intl #optional
#          ini-values: "post_max_size=256M" #optional
#      - name: Check PHP Version
#        run: php -v
#      - run: sudo composer self-update
#      - run: >-
#          composer require symfony/framework-bundle:${SYMFONY_VERSION}
#          --no-update
#        env:
#          SYMFONY_VERSION: '${{ matrix.SYMFONY_VERSION }}'
#      - run: composer install --prefer-dist --no-interaction
#      - run: ./src/BeSimple/SoapClient/Tests/bin/phpwebserver.sh
#      - run: ./src/BeSimple/SoapClient/Tests/bin/axis.sh
#      - run: bin/simple-phpunit