name: Workflow
on: [push]
jobs:
  php_8_job:
    runs-on: '${{ matrix.os }}'
    container: ubuntu:latest
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.0']
        include:
          - os: ubuntu-18.04
            SYMFONY_VERSION: 3.4.*
            SYMFONY_PHPUNIT_VERSION: '9.5'

    services:
      rabbit:
        image: pcloud/rabbitmq-stomp
        options: --hostname rabbit
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest

    steps:
      - uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl,soap,mongodb,apcu   #optional
          ini-values: "post_max_size=256M" #optional
      - name: Check PHP Version
        run: php -v
      - run: sudo apt-get update
      - run: sudo apt-get -y install iputils-ping
      - name: Checking rabbitmq
        run: ping rabbit -c 2
      - run: sudo composer self-update
      - run: sudo apt-get install -y libxml2-dev
      - run: >-
          composer require symfony/framework-bundle:${SYMFONY_VERSION}
          --no-update
        env:
          SYMFONY_VERSION: '${{ matrix.SYMFONY_VERSION }}'
          SYMFONY_PHPUNIT_VERSION: '${{ matrix.SYMFONY_PHPUNIT_VERSION }}'
      - run: composer install --prefer-dist --no-interaction
      - run: bin/simple-phpunit --coverage-text

  php_7_job:
    runs-on: '${{ matrix.os }}'
    container: ubuntu:latest
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']
        include:
          - os: ubuntu-18.04
            SYMFONY_VERSION: 3.4.*
            SYMFONY_PHPUNIT_VERSION: '9.5'

    services:
      rabbit:
        image: pcloud/rabbitmq-stomp
        options: --hostname rabbit
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest

    steps:
      - uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl,soap,mongodb,apcu
          ini-values: "post_max_size=256M"
      - name: Check PHP Version
        run: php -v
      - run: sudo apt-get update
      - run: sudo apt-get -y install iputils-ping
      - name: Checking rabbitmq
        run: ping rabbit -c 2
      - run: sudo composer self-update
      - run: sudo apt-get install -y libxml2-dev
      - run: >-
          composer require symfony/framework-bundle:${SYMFONY_VERSION}
          --no-update
        env:
          SYMFONY_VERSION: '${{ matrix.SYMFONY_VERSION }}'
          SYMFONY_PHPUNIT_VERSION: '${{ matrix.SYMFONY_PHPUNIT_VERSION }}'
      - run: composer install --prefer-dist --no-interaction
      - run: bin/simple-phpunit --coverage-text